model: nuqe

#
# WMT2018-NUQE OPTION
#
# what to predict
predict-target: true
predict-gaps: false
predict-source: false

# format of files
# (WMT18+ has added GAP tags)
wmt18-format: true

#
# MAIN OPTIONS (running args)
#
experiment-name: NuQE WMT18 en_de.nmt

#
# GENERAL OPTIONS
#
# random
seed: 42

# logging
debug: false
# output-dir: null  # mlflow will create one if this is null
mlflow-tracking-uri: mlruns/

# save and load
resume: false

#
# DATA OPTIONS


wmt18-format: true
train-source: WMT19/train.src
train-target: WMT19/train.mt
train-target-tags: WMT19/train.tags
train-alignments: WMT19/train.src-mt.alignments

valid-source: WMT19/dev.src
valid-target: WMT19/dev.mt
valid-target-tags: WMT19/dev.tags
valid-alignments: WMT19/dev.src-mt.alignments

# vocabulary
# source-vocab: null
source-vocab-min-frequency: 2
# source-vocab-size: null
# target-vocab: null
target-vocab-min-frequency: 2
# target-vocab-size: null
keep-rare-words-with-embeddings: true
add-embeddings-vocab: false

# embeddings
# pip-install the polyglot package to use these
# embeddings-format: polyglot
# source-embeddings: data/embeddings2/en/embeddings_pkl.tar.bz2
# target-embeddings: data/embeddings2/de/embeddings_pkl.tar.bz2

# load and save data (preprocessed datasets and built vocabs)
# save-data: null
# load-data: null

#
# MODEL OPTIONS
#
# embeddings
source-embeddings-size: 50
target-embeddings-size: 50

# network
hidden-sizes: [400, 200, 100, 50]
# output-size: 50
dropout: 0.0
embeddings-dropout: 0.5
freeze-embeddings: false
bad-weight: 3.0

#
# TRAINING OPTIONS
#
epochs: 3
shuffle: true
train-batch-size: 64
valid-batch-size: 64

# How and when to save the model
checkpoint-validation-epochs: 1
checkpoint-save: true
checkpoint-keep-only-best: 1
checkpoint-early-stop-patience: 10

#
# TRAINING OPTIMIZATION
#
optimizer: adam
learning-rate: 0.001

#
# QUETCH OPTIONS
#
window-size: 3
max-aligned: 5
